
plugins:
  - jekyll-remote-theme
remote_theme: BDHU/minimalist
title: Egecan Şen
email: benegecansen@gmail.com

logo: /assets/img/logo.jpg
description: Test Automation Engineer
show_downloads: false

sidebar:
  - name: Skills
  - name: Selenium - UI Automation
  - name: Appium - Mobile UI Automation
  - name: Rest Assured - API Automation
  - name: Github - Version control
  - name: Intermediate level Java
  - name: Intermediate level Maven
