plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
remote_theme: BDHU/minimalist
title: Egecan Şen
logo: /assets/img/logo.jpg
description: Test Automation Engineer
show_downloads: true
color-scheme: dark

sidebar:
  - name: LinkedIn
    icon: <i class="bi bi-linkedin"></i>
    link: https://www.linkedin.com/in/egecan-%C5%9Fen-887482202/
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/egecansen
  - name: Email
    icon: <i class="fa-solid fa-pen"></i>
    link: mailto:benegecansen@gmail.com

github: [metadata]
