version: '3'
services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - gem-cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  gem-cache: